data_dir: "/root/autodl-tmp/SEED_3D"
#data_dir: "/root/deap/SEED_3D"
save_dir: "/root/autodl-tmp/model_02"

train: true
epochs: 100
batch_size: 128
learning_rate: 8e-5
lr_scheduler: "cos"
if_wandb: false

device:
  - "cuda"

model: "DeapMamba"
dataset: "SEED"
mmmamba:
  mm_input_size: 512
  mm_output_sizes:
#    - 512
    - 768
    - 1024
#    - 768
#    - 512
  dropout: 0.1
  activation: "Tanh"
  causal: false
  mamba_config:
    d_state: 12
    expand: 2
    d_conv: 4
    bidirectional: true

num_classes: 3

input:
  T: 6   # 窗口长度
  C: 5   # 原始通道数（内部会选后 4 通道）
  H: 8
  W: 9

seed: 42
