# ——— SEED-VII 训练配置示例 ———

# 数据相关路径
data_dir: "/root/autodl-tmp/SEED_VII_3D"
save_dir: "/root/autodl-tmp/model"

# 训练开关 & 超参数
train: true
epochs: 100
batch_size: 128
learning_rate: 8e-5
lr_scheduler: "plateau"     # 可选 "cos" 或 "none"
if_wandb: false

# 设备
device:
  - "cuda"

# 模型 & Mamba 参数
model: "DeapMamba"      # 只是一个标记
dataset: "SEED-VII"
mmmamba:
  mm_input_size: 512
  mm_output_sizes:
    - 512
  dropout: 0.1
  activation: "Tanh"
  causal: false
  mamba_config:
    d_state: 12
    expand: 2
    d_conv: 4
    bidirectional: true

# 类别数：SEED-VII 如果要做 7 分类，就改成 7；二分类就 2；三分类（Sad/Happy/Neutral）就 3。
num_classes: 7

# 输入尺寸：T=滑窗帧数，C=通道数（DE/PSD 都是 5 个频段），H=8，W=9
input:
  T: 6
  C: 5
  H: 8
  W: 9

# 随机种子（可选）
seed: 42
