# only_PSD.yaml
data_dir: "/root/autodl-tmp/SEED_VII_3D"
save_dir: "/root/autodl-tmp/model_psd"

train: true
epochs: 100
batch_size: 128
learning_rate: 8e-5
lr_scheduler: "cos"
if_wandb: false

device:
  - "cuda"

mmmamba:
  mm_input_size: 512
  mm_output_sizes:
    - 512
  dropout: 0.1
  causal: false
  mamba_config:
    d_state: 12
    expand: 2
    d_conv: 4
    bidirectional: false

num_classes: 7

input:
  T: 6
  C: 5
  H: 8
  W: 9

seed: 42
